name = "FiniteDiscreteMeasure"
uuid = "97815211-d2e1-4849-9c09-28728ec73e5e"
authors = ["Davi Barreira <davisbarreira@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
